# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ChattingRoom(object):
    def setupUi(self, ChattingRoom):
        ChattingRoom.setObjectName("ChattingRoom")
        ChattingRoom.resize(800, 637)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/main.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ChattingRoom.setWindowIcon(icon)
        ChattingRoom.setStyleSheet("background-image: url(:/image/a.jpg);")
        self.centralwidget = QtWidgets.QWidget(ChattingRoom)
        self.centralwidget.setObjectName("centralwidget")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(490, 570, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("background-image: url(:/image/e.jpg);")
        self.exitButton.setObjectName("exitButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 30, 731, 441))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-image: url(:/image/d.jpg);")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_1.setEnabled(False)
        self.pushButton_1.setGeometry(QtCore.QRect(70, 50, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 50, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QtCore.QRect(530, 50, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 250, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(70, 250, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setGeometry(QtCore.QRect(530, 250, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.progressBar_1 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_1.setEnabled(False)
        self.progressBar_1.setGeometry(QtCore.QRect(70, 140, 118, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_1.setFont(font)
        self.progressBar_1.setMinimum(0)
        self.progressBar_1.setMaximum(10)
        self.progressBar_1.setProperty("value", 2)
        self.progressBar_1.setObjectName("progressBar_1")
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_2.setEnabled(False)
        self.progressBar_2.setGeometry(QtCore.QRect(280, 140, 118, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_2.setFont(font)
        self.progressBar_2.setMaximum(10)
        self.progressBar_2.setProperty("value", 2)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_3.setEnabled(False)
        self.progressBar_3.setGeometry(QtCore.QRect(530, 140, 118, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_3.setFont(font)
        self.progressBar_3.setMaximum(10)
        self.progressBar_3.setProperty("value", 2)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_4 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_4.setEnabled(False)
        self.progressBar_4.setGeometry(QtCore.QRect(70, 340, 118, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_4.setFont(font)
        self.progressBar_4.setMaximum(10)
        self.progressBar_4.setProperty("value", 2)
        self.progressBar_4.setObjectName("progressBar_4")
        self.progressBar_5 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_5.setEnabled(False)
        self.progressBar_5.setGeometry(QtCore.QRect(280, 340, 118, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_5.setFont(font)
        self.progressBar_5.setMaximum(10)
        self.progressBar_5.setProperty("value", 2)
        self.progressBar_5.setObjectName("progressBar_5")
        self.progressBar_6 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_6.setEnabled(False)
        self.progressBar_6.setGeometry(QtCore.QRect(530, 340, 118, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_6.setFont(font)
        self.progressBar_6.setStyleSheet("background: transparent")
        self.progressBar_6.setMaximum(10)
        self.progressBar_6.setProperty("value", 2)
        self.progressBar_6.setObjectName("progressBar_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(50, 40, 161, 131))
        self.groupBox_2.setStyleSheet("background: transparent")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(260, 40, 161, 131))
        self.groupBox_3.setStyleSheet("background: transparent")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(510, 40, 161, 131))
        self.groupBox_4.setStyleSheet("background: transparent")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(50, 240, 161, 131))
        self.groupBox_5.setStyleSheet("background: transparent")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(QtCore.QRect(260, 240, 161, 131))
        self.groupBox_6.setStyleSheet("background: transparent")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setGeometry(QtCore.QRect(510, 240, 161, 131))
        self.groupBox_7.setStyleSheet("background: transparent")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_7.raise_()
        self.groupBox_5.raise_()
        self.groupBox_4.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_6.raise_()
        self.pushButton_1.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_5.raise_()
        self.pushButton_4.raise_()
        self.pushButton_6.raise_()
        self.progressBar_1.raise_()
        self.progressBar_2.raise_()
        self.progressBar_3.raise_()
        self.progressBar_4.raise_()
        self.progressBar_5.raise_()
        self.progressBar_6.raise_()
        self.userName = QtWidgets.QLineEdit(self.centralwidget)
        self.userName.setGeometry(QtCore.QRect(210, 510, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.userName.setFont(font)
        self.userName.setObjectName("userName")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 520, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background: transparent")
        self.label.setObjectName("label")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setEnabled(False)
        self.loginButton.setGeometry(QtCore.QRect(400, 530, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("background-image: url(:/image/e.jpg);")
        self.loginButton.setObjectName("loginButton")
        self.logoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutButton.setEnabled(False)
        self.logoutButton.setGeometry(QtCore.QRect(580, 530, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.logoutButton.setFont(font)
        self.logoutButton.setStyleSheet("background-image: url(:/image/e.jpg);")
        self.logoutButton.setObjectName("logoutButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 570, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: transparent")
        self.label_2.setObjectName("label_2")
        self.passWord = QtWidgets.QLineEdit(self.centralwidget)
        self.passWord.setGeometry(QtCore.QRect(210, 560, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.passWord.setFont(font)
        self.passWord.setObjectName("passWord")
        self.registerButton = QtWidgets.QPushButton(self.centralwidget)
        self.registerButton.setGeometry(QtCore.QRect(490, 490, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.registerButton.setFont(font)
        self.registerButton.setStyleSheet("background-image: url(:/image/e.jpg);")
        self.registerButton.setObjectName("registerButton")
        ChattingRoom.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ChattingRoom)
        self.statusbar.setObjectName("statusbar")
        ChattingRoom.setStatusBar(self.statusbar)

        self.retranslateUi(ChattingRoom)
        QtCore.QMetaObject.connectSlotsByName(ChattingRoom)

    def retranslateUi(self, ChattingRoom):
        _translate = QtCore.QCoreApplication.translate
        ChattingRoom.setWindowTitle(_translate("ChattingRoom", "MeiCorl\'s Chatting Room"))
        self.exitButton.setText(_translate("ChattingRoom", "Exit"))
        self.groupBox.setTitle(_translate("ChattingRoom", "Please choose a chatting room to jion!"))
        self.pushButton_1.setText(_translate("ChattingRoom", "Room1"))
        self.pushButton_2.setText(_translate("ChattingRoom", "Room2"))
        self.pushButton_3.setText(_translate("ChattingRoom", "Room3"))
        self.pushButton_5.setText(_translate("ChattingRoom", "Room5"))
        self.pushButton_4.setText(_translate("ChattingRoom", "Room4"))
        self.pushButton_6.setText(_translate("ChattingRoom", "Room6"))
        self.label.setText(_translate("ChattingRoom", " User Name"))
        self.loginButton.setText(_translate("ChattingRoom", "Login"))
        self.logoutButton.setText(_translate("ChattingRoom", "Logout"))
        self.label_2.setText(_translate("ChattingRoom", "Password"))
        self.registerButton.setText(_translate("ChattingRoom", "Register"))

import img_rc
